sudo: false

git:
  submodules: false

language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly

env:
  - JVERSION_TEST=staging

addons:
  apt:
    packages:
    - gdb

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - git clone -b "$JVERSION_TEST" https://github.com/joomla/joomla-cms.git Tests/environments/"$JVERSION_TEST"
  - chmod +x .travis.scripts/debug-core.sh

install:
  - composer selfupdate
  - composer install

before_script:
  # enable core dumps
  - ulimit -c unlimited -S
  - mysql -u root -e 'create database fof_test;'
  - mysql -u root -e "CREATE USER 'fof_db'@'localhost' IDENTIFIED BY 'fof';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fof_test.* TO 'fof_db'@'%' IDENTIFIED BY 'fof';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fof_test.* TO 'fof_db'@'localhost' IDENTIFIED BY 'fof';"
  - mysql -u root -e 'FLUSH PRIVILEGES;'

after_script:
  - cat Tests/debug.txt

after_failure:
  - find . -iname 'core*' ! -iname '*.php' -exec .travis.scripts/debug-core.sh {} \;
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
