sudo: false

git:
  submodules: false

language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - JVERSION_TEST=staging
  - JVERSION_TEST=3.7.x
  - JVERSION_TEST=4.0-dev

matrix:
  fast_finish: true
  include:
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next travis ci update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: JVERSION_TEST=staging
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next travis ci update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: JVERSION_TEST=3.7.x
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next travis ci update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: JVERSION_TEST=4.0-dev
  allow_failures:
     - php: hhvm
     - php: 7.1
     - php: 7.0
     - php: 5.6
       env: JVERSION_TEST=3.7.x
     - php: 5.6
       env: JVERSION_TEST=4.0-dev
     - php: 5.5
       env: JVERSION_TEST=3.7.x
     - php: 5.5
       env: JVERSION_TEST=4.0-dev
     - php: 5.4
       env: JVERSION_TEST=3.7.x
     - php: 5.4
       env: JVERSION_TEST=4.0-dev
     - php: 5.3
       env: JVERSION_TEST=3.7.x
     - php: 5.3
       env: JVERSION_TEST=4.0-dev

branches:
  only:
    - development
    - debug-travis

before_install:
  - git clone -b "$JVERSION_TEST" https://github.com/joomla/joomla-cms.git Tests/environments/"$JVERSION_TEST"

install:
  - composer selfupdate
  - composer install

before_script:
  - mysql -u root -e 'create database fof_test;'
  - mysql -u root -e "CREATE USER 'fof_db'@'localhost' IDENTIFIED BY 'fof';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fof_test.* TO 'fof_db'@'%' IDENTIFIED BY 'fof';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fof_test.* TO 'fof_db'@'localhost' IDENTIFIED BY 'fof';"
  - mysql -u root -e 'FLUSH PRIVILEGES;'

after_script:
  - cat Tests/debug.txt

notifications:
  email: false
